config/routes.rb
JoshuaPaling::Application.routes.draw do

  devise_for :users, :skip => [:registrations]
    as :user do # solution 2 from https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  root :to => 'posts#index'

  resources :posts, only: [:index] do
    resources :comments, :only => [:create]
  end

  get 'posts/category/:slug', to: 'posts#category', as: 'posts_category'
  get 'post/:slug', to: 'posts#show', as: 'post'

  get '/about', :to => 'pages#about'
  get '/o-and-x', :to => 'pages#o_and_x'
  get '/conways', :to => 'pages#conways'

  namespace :admin do
    root 'posts#index'
    resources :posts, param: :slug
    resources :categories
    resources :images
  end

  get '/404', :to => 'errors#not_found'
  get '/500', :to => 'errors#internal_error'
  get '/422', :to => 'errors#unprocessable_entity'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :posts, :through => :categorizations

  validates_presence_of :name, :slug
  validates_uniqueness_of :name, :slug
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /admin/categories
  def index
    @categories = Category.all
  end

  # GET /admin/categories/new
  def new
    @category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to [:admin, @category], notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/categories/1
  def update
    if @category.update(category_params)
      redirect_to [:admin, @category], notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/categories/1
  def destroy
    @category.destroy
    redirect_to admin_categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name, :slug)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= simple_form_for([:admin, @category]) do |f| %>
  <%= f.error_notification %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6">
        <%= f.input :name %>
      </div>
      <div class="col-sm-6">
        <%= f.input :slug %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <%= f.error :base %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

app/views/admin/categories/index.html.erb
<h1>Listing categories</h1>
<%= link_to 'New Category', new_admin_category_path, class: 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.slug %></td>
        <td>
          <%= link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-sm btn-default' %>
          <%= link_to 'Show', posts_category_path(category.slug), target: :blank, class: 'btn btn-sm btn-default' %>
          <%= link_to raw('<span class="glyphicon glyphicon-trash"></span>'), [:admin, category],
            method: :delete,
            class: 'btn btn-sm btn-default',
            data: { confirm: 'Are you sure?' }
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_admin_category_path, class: 'btn btn-primary' %>

app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>