config/routes.rb
JoshuaPaling::Application.routes.draw do

  devise_for :users, :skip => [:registrations]
    as :user do # solution 2 from https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  root :to => 'posts#index'

  resources :posts, only: [:index] do
    resources :comments, :only => [:create]
  end

  get 'posts/category/:slug', to: 'posts#category', as: 'posts_category'
  get 'post/:slug', to: 'posts#show', as: 'post'

  get '/about', :to => 'pages#about'
  get '/o-and-x', :to => 'pages#o_and_x'
  get '/conways', :to => 'pages#conways'

  namespace :admin do
    root 'posts#index'
    resources :posts, param: :slug
    resources :categories
    resources :images
  end

  get '/404', :to => 'errors#not_found'
  get '/500', :to => 'errors#internal_error'
  get '/422', :to => 'errors#unprocessable_entity'
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :categorizations
  has_many :categories, :through => :categorizations

  validates_presence_of :blurb, :title, :published_at, :slug
  validates_uniqueness_of :slug

  default_scope { order('published_at DESC') }
  scope :published, -> { where(:published => true) }
  scope :unpublished, -> { where(:published => false) }

  after_initialize :set_defaults

  def content field
    if field
      MarkdownService.new.render(field)
    else
      ''
    end
  end

  # set defaults - taken from http://stackoverflow.com/questions/328525/what-is-the-best-way-to-set-default-values-in-activerecord
  def set_defaults
    self.published_at  ||= Time.now
  end

  def to_param
    slug
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /admin/posts
  def index
    @posts = Post.all
  end

  # GET /admin/posts/new
  def new
    @post = Post.new
  end

  # GET /admin/posts/1/edit
  def edit
  end

  # POST /admin/posts
  def create
    @post = Post.new(admin_post_params)

    if @post.save
      redirect_to admin_posts_path, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/posts/1
  def update
    if @post.update(admin_post_params)
      redirect_to admin_posts_path, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/posts/1
  def destroy
    @post.destroy
    redirect_to admin_posts_path, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_slug(params[:slug])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_post_params
      params.require(:post).permit!
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  # GET /posts.atom
  def index
    @posts = Post.published.page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.atom
    end
  end

  def category
    @category = Category.find_by_slug(params[:slug])
    @posts = Post.published.joins(:categories).where("categories.id = ?", @category).page(params[:page]).per(10)

    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @posts }
      format.atom
    end
  end

  # GET /post/my-slug
  # GET /post/my-slug.json
  def show
    @post = Post.find_by_slug(params[:slug])

    if @post.nil?
      raise ActiveRecord::RecordNotFound
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  private

  def person_params
    params.require(:post).permit(:published, :published_at, :slug, :title, :category_ids, :blurb, :body)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<article class="post">

  <header>
    <h1>
      <%= link_to_unless_current post.title, post_path(post.slug) %>
      <%# if user_signed_in? %>
        &nbsp;
        <%#= link_to "(edit)", edit_admin_post_url(post.id), target: :blank %>
      <%# end %>
    </h1>
    <p>
      Posted
      <strong><%= post.published_at.strftime('%e %b %Y at %l%P') %></strong>
      in
      <%= post.categories.map{|c| link_to c.name, posts_category_path(c.slug) }.join(" &bull; ").html_safe %>
      <% if params[:action] == 'show' %>
        <%= render :partial => 'social_links' %>
      <% end %>
    </p>
  </header>

  <%= post.content(post.blurb).html_safe %>
  <% if params[:action] == 'show' %>
    <%= post.content(post.body).html_safe %>
    <footer>
      <%= render :partial => 'social_links' %>
    </footer>
  <% else %>
    <footer>
      <%= link_to "More ›", post_path(post.slug), class: 'more' %>
    </footer>
  <% end %>

  <% #DevHub q › why can you access the model direct form the view? And shouldn't content rendering be the responsibility of the view? %>
</article>

app/views/posts/_social_links.html.erb
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style">
<a class="addthis_button_tweet"></a>
<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
</div>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-51ea66074c301203"></script>
<!-- AddThis Button END -->

app/views/posts/index.html.erb
<h1 class="page-title"><%= 'Blog: ' + (( @category.nil? )? 'All Posts' : @category.name) %></h1>
<%= paginate @posts %>

<%= render :partial => @posts %>

<%= paginate @posts %>

app/views/posts/show.html.erb
<h1 class="page-title">BLOG</h1>
<%= render :partial => @post %>

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'joshuapaling'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>