config/routes.rb
JoshuaPaling::Application.routes.draw do

  devise_for :users, :skip => [:registrations]
    as :user do # solution 2 from https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  root :to => 'posts#index'

  resources :posts, only: [:index] do
    resources :comments, :only => [:create]
  end

  get 'posts/category/:slug', to: 'posts#category', as: 'posts_category'
  get 'post/:slug', to: 'posts#show', as: 'post'

  get '/about', :to => 'pages#about'
  get '/o-and-x', :to => 'pages#o_and_x'
  get '/conways', :to => 'pages#conways'

  namespace :admin do
    root 'posts#index'
    resources :posts, param: :slug
    resources :categories
    resources :images
  end

  get '/404', :to => 'errors#not_found'
  get '/500', :to => 'errors#internal_error'
  get '/422', :to => 'errors#unprocessable_entity'
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /admin/images
  def index
    @images = Image.all
  end

  # GET /admin/images/1
  def show
  end

  # GET /admin/images/new
  def new
    @image = Image.new
  end

  # GET /admin/images/1/edit
  def edit
  end

  # POST /admin/images
  def create
    @image = Image.new(image_params)

    if @image.save
      redirect_to admin_images_path, notice: 'Image was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/images/1
  def update
    if @image.update(image_params)
      redirect_to admin_images_path, notice: 'Image was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/images/1
  def destroy
    @image.destroy
    redirect_to admin_images_url, notice: 'Image was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def image_params
      params.require(:image).permit(:alt, :image)
    end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/views/admin/images/_form.html.erb
<%= simple_form_for([:admin, @image]) do |f| %>
  <%= f.error_notification %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-6">
        <%= f.input :image %>
      </div>
      <div class="col-sm-6">
        <%= f.input :alt %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <%= f.error :base %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

app/views/admin/images/index.html.erb
<h1>Listing images</h1>
<%= link_to 'New Image', new_admin_image_path, class: 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Image</th>
      <th>Path</th>
      <th>Alt</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image_tag image.image.thumb %></td>
        <td><%= image.image %></td>
        <td><%= image.alt %></td>
        <td>
          <%= link_to 'Edit', edit_admin_image_path(image), class: 'btn btn-sm btn-default' %>
          <%= link_to raw('<span class="glyphicon glyphicon-trash"></span>'), [:admin, image],
            method: :delete,
            class: 'btn btn-sm btn-default',
            data: { confirm: 'Are you sure?' }
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_admin_image_path, class: 'btn btn-primary' %>

app/views/admin/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>