config/routes.rb
JoshuaPaling::Application.routes.draw do

  devise_for :users, :skip => [:registrations]
    as :user do # solution 2 from https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  root :to => 'posts#index'

  resources :posts, only: [:index] do
    resources :comments, :only => [:create]
  end

  get 'posts/category/:slug', to: 'posts#category', as: 'posts_category'
  get 'post/:slug', to: 'posts#show', as: 'post'

  get '/about', :to => 'pages#about'
  get '/o-and-x', :to => 'pages#o_and_x'
  get '/conways', :to => 'pages#conways'

  namespace :admin do
    root 'posts#index'
    resources :posts, param: :slug
    resources :categories
    resources :images
  end

  get '/404', :to => 'errors#not_found'
  get '/500', :to => 'errors#internal_error'
  get '/422', :to => 'errors#unprocessable_entity'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  devise :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  def name
    email
  end
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :posts, :through => :categorizations

  validates_presence_of :name, :slug
  validates_uniqueness_of :name, :slug
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :categorizations
  has_many :categories, :through => :categorizations

  validates_presence_of :blurb, :title, :published_at, :slug
  validates_uniqueness_of :slug

  default_scope { order('published_at DESC') }
  scope :published, -> { where(:published => true) }
  scope :unpublished, -> { where(:published => false) }

  after_initialize :set_defaults

  def content field
    if field
      MarkdownService.new.render(field)
    else
      ''
    end
  end

  # set defaults - taken from http://stackoverflow.com/questions/328525/what-is-the-best-way-to-set-default-values-in-activerecord
  def set_defaults
    self.published_at  ||= Time.now
  end

  def to_param
    slug
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  before_filter :authenticate_user!
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /admin/images
  def index
    @images = Image.all
  end

  # GET /admin/images/1
  def show
  end

  # GET /admin/images/new
  def new
    @image = Image.new
  end

  # GET /admin/images/1/edit
  def edit
  end

  # POST /admin/images
  def create
    @image = Image.new(image_params)

    if @image.save
      redirect_to admin_images_path, notice: 'Image was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/images/1
  def update
    if @image.update(image_params)
      redirect_to admin_images_path, notice: 'Image was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/images/1
  def destroy
    @image.destroy
    redirect_to admin_images_url, notice: 'Image was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def image_params
      params.require(:image).permit(:alt, :image)
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /admin/posts
  def index
    @posts = Post.all
  end

  # GET /admin/posts/new
  def new
    @post = Post.new
  end

  # GET /admin/posts/1/edit
  def edit
  end

  # POST /admin/posts
  def create
    @post = Post.new(admin_post_params)

    if @post.save
      redirect_to admin_posts_path, notice: 'Post was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /admin/posts/1
  def update
    if @post.update(admin_post_params)
      redirect_to admin_posts_path, notice: 'Post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/posts/1
  def destroy
    @post.destroy
    redirect_to admin_posts_path, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_slug(params[:slug])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_post_params
      params.require(:post).permit!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :load_categories

  def load_categories
    @test_string = "Hello World"
    @categories_all = Category.all
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
  end

  def internal_error
  end

  def unprocessable_entity
  end
end

app/controllers/my_devise_controller.rb
class MyDeviseController < ApplicationController

  layout :layout

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) ||
      case resource_or_scope.class.name
      when "User"
        admin_root_path
      else
        super
      end
  end

  def after_sign_out_path_for(resource_or_scope)
    case resource_or_scope
    when :user
      new_user_session_path
    end
  end

  def signed_in_root_path(resource)
    case resource.class.name
    when "User"
      admin_root_path
    else
      super
    end
  end

  private

    def layout
      if devise_controller? && devise_mapping.name == :user
        'admin'
      else
        'layouts/application'
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def o_and_x
  end

  def conways
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  # GET /posts.atom
  def index
    @posts = Post.published.page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.atom
    end
  end

  def category
    @category = Category.find_by_slug(params[:slug])
    @posts = Post.published.joins(:categories).where("categories.id = ?", @category).page(params[:page]).per(10)

    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @posts }
      format.atom
    end
  end

  # GET /post/my-slug
  # GET /post/my-slug.json
  def show
    @post = Post.find_by_slug(params[:slug])

    if @post.nil?
      raise ActiveRecord::RecordNotFound
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  private

  def person_params
    params.require(:post).permit(:published, :published_at, :slug, :title, :category_ids, :blurb, :body)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


  # from https://coderwall.com/p/jzofog
  def flash_class(level)
      case level.to_sym
          when :notice then "alert alert-info"
          when :success then "alert alert-success"
          when :error then "alert alert-danger"
          when :alert then "alert alert-warning"
      end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_admin_header.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Joss' Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'admin/posts' %>">
          <%= link_to 'Posts', admin_posts_path %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'admin/categories' %>">
          <%= link_to 'Categories', admin_categories_path %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'admin/images' %>">
          <%= link_to 'Images', admin_images_path %>
        </li>
      </ul>

      <% begin current_user.email %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to (raw('<span class="glyphicon glyphicon-user"></span> &nbsp;&nbsp;') + current_user.email), edit_user_registration_path %>
          </li>
          <li>
            <%= link_to raw('<span class="glyphicon glyphicon-log-out"></span>'), destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% rescue %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_footer.html.erb
<footer class="main">
  <p>
    Powered by: <%= link_to 'rails-3-2-intro-blog', 'https://github.com/reinteractive-open/rails-3-2-intro-blog' %>
    Developed at: <%= link_to 'InstallFest 2013', 'http://reinteractive.net/service/installfest' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="main">
  <h1 class="site-title">Joshua Paling</h1>
  <h2>(aka Joss)<h2>
  <nav>
    <% currentClass = (request.fullpath != '/about' && request.fullpath != '/o-and-x')? 'current' : '' %>
    <%= link_to 'blog', posts_path, class: currentClass %>

    <% currentClass = (request.fullpath == '/about')? 'current' : '' %>
    <%= link_to 'about', '/about', class: currentClass %>

    <% currentClass = (request.fullpath == '/o-and-x')? 'current' : '' %>
    <%#= link_to 'o & x', '/o-and-x', class: currentClass %>

    <%= link_to raw('<span aria-hidden="true" class="icon-github"></span>'), 'https://github.com/joshuapaling', target: 'blank' %>
    <%= link_to raw('<span aria-hidden="true" class="icon-stackoverflow"></span>'), 'http://stackoverflow.com/users/1373987/joshua-paling', target: 'blank' %>
    <%= link_to raw('<span aria-hidden="true" class="icon-twitter"></span>'), 'https://twitter.com/joshuapaling', target: 'blank' %>
    <%= link_to raw('<span aria-hidden="true" class="icon-feed"></span>'), posts_path(:atom), target: 'blank' %>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
  <h1 class="page-title">Categories</h1>
  <ul class="side-nav">
    <li><%= link_to 'ALL POSTS', posts_path %></li>
    <% @categories_all.each do |c| %>
      <li><%= link_to c.name, posts_category_path(c.slug) %></li>
    <% end %>
  </ul>

  <a class="twitter-timeline" href="https://twitter.com/joshuapaling" data-widget-id="345441050686550016">Tweets by @joshuapaling</a>

  <!-- twitter widget -->
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Joshua Paling</title>
    <%= stylesheet_link_tag    "admin/application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= auto_discovery_link_tag(:atom, posts_path(:atom)) %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render :partial => 'layouts/admin_header' %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "admin/application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joshua Paling</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= auto_discovery_link_tag(:atom, posts_path(:atom)) %>

  <!-- google analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41194648-1', 'joshuapaling.com');
    ga('send', 'pageview');

  </script>

</head>
<body>
  <div class="fixed-width">
    <%= render :partial => 'layouts/header' %>

    <div id="main">
        <div id="content-area">
          <%= yield %>
        </div>
        <%= render :partial => 'layouts/sidebar' %>

        <div style="clear: both;"></div>
    </div>

    <%= render :partial => 'layouts/footer' %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<div class="about-page">
  <h1 class="page-title">About Me</h1>
  <p>Hello! I'm Joss, a 28 year old full stack web developer from Sydney, Australia. I currently use Ruby on Rails and CakePHP. You can contact me at <a href='&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#106;&#111;&#115;&#104;&#117;&#97;&#46;&#112;&#97;&#108;&#105;&#110;&#103;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;'>&#106;&#111;&#115;&#104;&#117;&#97;&#46;&#112;&#97;&#108;&#105;&#110;&#103;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;</a>.</p>

  <p>
    I'm married to Jess.
    <%= image_tag "jess-joss.jpg" %>
  </p>
  <p>
    These are our twins, Annika and Luke.
    <%= image_tag "luke-annika.jpg" %>
  </p>
  <p
  >When I'm not coding or changing nappies, I like surfing,
    <%= image_tag "joss-surfing.jpg" %>
  </p>

  <p>
    and skateboarding.
    <%= image_tag "skating.jpg" %>
  </p>
</div>

app/views/pages/conways.html.erb
<script>
 $(function(){
  $('.cell').click(function(){
    $(this).toggleClass('alive');
  });
 });
</script>

<div class="conways">
  <h1 class="page-title">Conway's Game of Life - Virtual Scrap Paper</h1>
  <p>Rather than running through scenarios on scrap paper, use the board below.</p>

  <p>I also wrote <a href="/post/tips-for-conways-game-of-life" target="_blank">a post</a> with suggested steps for newer devs and their mentors (TL;DR: don't dive straight into TDD).</p>

  <h3>Rules:</h3>
  <p>If a <strong>live</strong> cell has <strong>two or three</strong> neighbours, it lives. Otherwise, it dies.</p>
  <p>If a <strong>dead</strong> cell has <strong>exactly three</strong> neighbours, it comes to life.</p>

  <div class="conways_world">
    <% for y in 0..9 %>
      <% for x in 0..9 %>
        <div class="cell">
          <%= x %>, <%= y %>
        </div>
      <% end %>
      <div style="clear: both;"></div>
    <% end %>
  </div>
</div>

app/views/pages/o_and_x.html.erb
<div class="about-page">
  <h1 class="page-title">o & x's</h1>
  <p>I normally use jQuery and Javascript. I want to learn backbone and coffee script, so I've used it to build a simple naughts and crosses game. At the moment, it's two-player only. Soon I'll update it so you can play vs. the computer.</p>

  <div id="backbone-container">

  </div>
</div>